---
# tasks file for ansible-role-prometheus
- name: create prometheus user
  user:
    name: prometheus
    createhome: no
    shell: /sbin/nologin

- include_tasks: node_exporter.yml

- block:
  - name: create prometheus conf directory
    file:
      path: /etc/prometheus/targets
      state: directory
      owner: root
      group: root
      mode: '0755'
  - name: create prometheus data directory
    file:
      path: '{{ prometheus_storage_path }}'
      state: directory
      owner: prometheus
      group: prometheus
      mode: '0755'
  - name: detect consul is installed
    stat:
      path: /usr/local/bin/consul
    register: consul_bin
  - include_tasks: blackbox_exporter.yml
  - include_tasks: alertmanager.yml
  - include_tasks: prometheus.yml
  when: prometheus_server_hostnames != None and inventory_hostname in prometheus_server_hostnames
