---
# tasks file for ansible-role-prometheus
- name: detect prometheus is installed
  stat:
    path: /usr/local/bin/prometheus
  register: prometheus_bin

- block:
  - name: download prometheus {{ PROMETHEUS_VERSION }}
    unarchive:
      src: https://github.com/prometheus/prometheus/releases/download/v{{ PROMETHEUS_VERSION }}/prometheus-{{ PROMETHEUS_VERSION }}.linux-amd64.tar.gz
      dest: /tmp
      remote_src: yes
  - name: install prometheus
    command: mv /tmp/prometheus-{{ PROMETHEUS_VERSION }}.linux-amd64/prometheus /usr/local/bin/prometheus
  - name: install promtool
    command: mv /tmp/prometheus-{{ PROMETHEUS_VERSION }}.linux-amd64/promtool /usr/local/bin/promtool
  when: not prometheus_bin.stat.exists

- name: copy prometheus conf file
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'
  notify: restart prometheus service

- name: copy file_sd_configs node
  template:
    src: node.yml.j2
    dest: /etc/prometheus/targets/node.yml
    owner: root
    group: root
    mode: '0644'

- name: copy file_sd_configs probe http
  template:
    src: probe_http.yml.j2
    dest: /etc/prometheus/targets/probe_http.yml
    owner: root
    group: root
    mode: '0644'
  when: blackbox_probe_http_targets != None

- name: detect consul-template conf directory
  stat:
    path: /etc/consul-template.d
  register: consul_template_conf_dir

- block:
  - name: copy node list update shell
    template:
      src: node_update.sh.j2
      dest: /etc/prometheus/targets/node_update.sh
      owner: root
      group: root
      mode: 0755
  - name: copy node dyna conf
    template:
      src: node.list.tmpl.j2
      dest: /etc/prometheus/targets/node.list.tmpl
      owner: root
      group: root
      mode: 0644
    notify: restart consul-template service
  - name: copy consul-template conf
    template:
      src: prometheus_node_dyna.conf.j2
      dest: /etc/consul-template.d/prometheus_node_dyna.conf
      owner: root
      group: root
      mode: 0644
    notify: restart consul-template service
  when: consul_template_conf_dir.stat.exists

- name: copy prometheus alert_rules file
  copy:
    src: templates/alert_rules.yml
    dest: /etc/prometheus/alert_rules.yml
    owner: root
    group: root
    mode: '0644'
  notify: restart prometheus service

- name: copy prometheus service file
  template:
    src: prometheus.service.j2
    dest: /usr/lib/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'

- name: daemon-reload
  systemd: daemon_reload=yes

- name: start prometheus service
  service:
    name: prometheus
    state: started
    enabled: yes
