---
# handlers file for ansible-role-prometheus
- name: restart prometheus service
  service:
    name: prometheus
    state: restarted
  tags: prometheus

- name: restart alertmanager service
  service:
    name: alertmanager
    state: restarted
  tags: prometheus

- name: restart blackbox_exporter service
  service:
    name: blackbox_exporter
    state: restarted
  tags: prometheus
