---
# handlers file for ansible-role-prometheus
- name: restart prometheus service
  service:
    name: prometheus
    state: restarted

- name: restart alertmanager service
  service:
    name: alertmanager
    state: restarted
  when: inventory_hostname == prometheus_server_hostnames[0]

- name: restart blackbox_exporter service
  service:
    name: blackbox_exporter
    state: restarted

- name: restart consul-template service
  service:
    name: consul-template
    state: restarted
  when: test_skip is undefined
